### ISSUE TITLE
Bug:  QUARANTINE doesnt get added to file

### ISSUE THREAD

**Issue by SchoolyB** [Solitude-Software-Solutions/OstrichDB#138]
When a file fails data and structural integrity checks it DOES get moved over to the `/quarintine` dir but this string:

`QuarantineStr: string = "\n# [QUARANTINED] [QUARANTINED] [QUARANTINED] [QUARANTINED]\n"`
is NOT being appended to the bottom of the file as It should be. A simple fix

**Comment by KhushiSharma0313** [comment]
I want to work on this, can you please assign it to me

**Comment by SchoolyB** [comment]
@KhushiSharma0313 Create your branch off the `development` branch.

**Comment by SchoolyB** [comment]
@KhushiSharma0313 Any progress with this issue? If not I can take care of it

**Comment by SchoolyB** [comment]
Deprecating this feature. Since all files will end up being compress & encrypted anyway I see no point in worrying about this for the future
