### ISSUE TITLE
Feature: Implement dot notation in OstrichDB

### ISSUE THREAD

**Issue by SchoolyB** [Solitude-Software-Solutions/OstrichDB#77]
This Idea comes from a comment in my latest YouTube video [here](https://www.youtube.com/watch?v=Xql6G7730RU) Commenter asks why not use dot notation in commands like:
 `NEW CLUSTER foo.bar` this would be the same as saying `NEW CLUSTER foo WITHIN COLLECTION bar` 
 or maybe `NEW CLUSTER bar WITHIN COLLECTION` foo???

I think this is an amazing idea. This would prevent the user from having to remember so may modifier tokens and long commands. I plan to investigate this further.

-----------------
Edit 3Oct2024
Here is a more detailed way showing how things should be

```
//There is no need to have dot notation for collections

//performing actions on clusters with dot notation
<action> cluster clu_name.clo_name <modifiers_if_needed> //If NOT in FOCUS MODE
<action> cluster clu_name //If focused on a collection
<action> //If focused on a cluster

//performing actions on records with dot notation
<action> record rec_name.clu_name.clo_name <modifiers_if_needed> //If NOT in FOCUS MODE
<action> record rec_name.clu_name <modifiers_if_needed> //If focused on a collection
<action> record rec_name of_type bool <modifiers_if_needed> //If focused on a cluster
```

**Comment by Kelimion** [comment]
I meant for `NEW CLUSTER foo.bar` to be analogous to `NEW CLUSTER bar WITHIN COLLECTION foo`. Reading from left to right, `bar` would be a member of `foo`. Think of it as a struct/record member.

**Comment by SchoolyB** [comment]
In progress

**Comment by SchoolyB** [comment]
:) https://github.com/Solitude-Software-Solutions/OstrichDB/commit/34e12950625e071397eb755247792c9bb8f05df0
